'use strict';
function mediaStatusClass(status){return status==='Pass'?'released':status==='Fail'?'rejected':'pending';}
function formatDate(value,withTime=false){if(!value)return '—';const d=new Date(value+(value.length===10?'T00:00:00':''));return Number.isFinite(d.getTime())?d.toLocaleString('en-MY',withTime?{dateStyle:'medium',timeStyle:'short'}:{dateStyle:'medium'}):value;}
const MEDIA_PAGE_SIZE=10;let mediaPage=1;
function renderMediaPagination(total){const pages=Math.max(1,Math.ceil(total/MEDIA_PAGE_SIZE));mediaPage=Math.min(mediaPage,pages);const start=total?(mediaPage-1)*MEDIA_PAGE_SIZE+1:0,end=Math.min(mediaPage*MEDIA_PAGE_SIZE,total);document.getElementById('media-page-summary').textContent=`Showing ${start}–${end} of ${total} records`;document.getElementById('media-page-controls').innerHTML=`<button class="media-page-button" data-media-page="${mediaPage-1}" ${mediaPage===1?'disabled':''} aria-label="Previous page">←</button>${Array.from({length:pages},(_,index)=>`<button class="media-page-button ${index+1===mediaPage?'is-active':''}" data-media-page="${index+1}" aria-label="Page ${index+1}" ${index+1===mediaPage?'aria-current="page"':''}>${index+1}</button>`).join('')}<button class="media-page-button" data-media-page="${mediaPage+1}" ${mediaPage===pages?'disabled':''} aria-label="Next page">→</button>`;}
function renderMediaRows(){const query=document.getElementById('media-search').value.trim().toLowerCase(),filter=document.getElementById('media-status').value;const rows=QCMediaStore.read().filter(r=>(!query||[r.id,r.media,r.lot,r.manufacturer].join(' ').toLowerCase().includes(query))&&(filter==='all'||r.status===filter));const pageRows=rows.slice((mediaPage-1)*MEDIA_PAGE_SIZE,mediaPage*MEDIA_PAGE_SIZE);document.getElementById('media-count').textContent=`${rows.length} ${rows.length===1?'record':'records'}`;document.getElementById('media-rows').innerHTML=pageRows.length?pageRows.map(r=>`<tr><td><select class="media-action-select" data-media-action="${r.id}" aria-label="Actions for ${r.id}"><option value="" selected disabled hidden>Action</option><option value="edit">Edit Media</option><option value="performance">Performance Testing</option></select></td><td><strong>${r.id}</strong></td><td>${r.media}</td><td>${r.manufacturer}</td><td>${r.lot}</td><td>${formatDate(r.dateReceived)}</td><td>${r.checkedBy||'—'}</td><td>${formatDate(r.checkedAt,true)}</td><td><span class="media-status media-status-${mediaStatusClass(r.status)}">${r.status}</span></td></tr>`).join(''):'<tr><td colspan="9" style="text-align:center;padding:32px;color:#8797a6">No QC media records match the current filter.</td></tr>';renderMediaPagination(rows.length);}
document.getElementById('media-rows').addEventListener('change',event=>{const select=event.target.closest('[data-media-action]');if(!select)return;const id=encodeURIComponent(select.dataset.mediaAction);location.href=select.value==='edit'?`Register_QC_Media.html?media=${id}`:`Media_Performance_Testing.html?media=${id}`;});
function downloadMediaExcel(){const rows=QCMediaStore.read(),escape=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'),audit=(row,step,key)=>row.performance?.[step]?.[key]||'',headers=['Media QC ID','Media Name','Manufacturer','Lot Number','Date Received','Checked By','Checked Date','Status','Performed By','Performed Date','Reviewed By','Reviewed Date','Endorsed By','Endorsed Date'],values=rows.map(row=>[row.id,row.media,row.manufacturer,row.lot,row.dateReceived,row.checkedBy,row.checkedAt,row.status,audit(row,'performed','by'),audit(row,'performed','at'),audit(row,'reviewed','by'),audit(row,'reviewed','at'),audit(row,'endorsed','by'),audit(row,'endorsed','at')]);const table=`<html xmlns:x="urn:schemas-microsoft-com:office:excel"><head><meta charset="utf-8"><style>table{border-collapse:collapse;font-family:Calibri,sans-serif}th{background:#107c41;color:#fff;font-weight:bold}th,td{border:1px solid #cfd8dc;padding:8px;white-space:nowrap}</style></head><body><table><thead><tr>${headers.map(x=>`<th>${escape(x)}</th>`).join('')}</tr></thead><tbody>${values.map(row=>`<tr>${row.map(x=>`<td>${escape(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></body></html>`,url=URL.createObjectURL(new Blob(['\ufeff',table],{type:'application/vnd.ms-excel;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=`QC-Media-Master-List-${new Date().toISOString().slice(0,10)}.xls`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
document.getElementById('media-export').addEventListener('click',downloadMediaExcel);
document.getElementById('media-page-controls').addEventListener('click',event=>{const button=event.target.closest('[data-media-page]');if(!button||button.disabled)return;mediaPage=Number(button.dataset.mediaPage);renderMediaRows();});document.getElementById('media-search').addEventListener('input',()=>{mediaPage=1;renderMediaRows();});document.getElementById('media-status').innerHTML='<option value="all">All statuses</option><option>Pending</option><option>Pass</option><option>Fail</option>';document.getElementById('media-status').addEventListener('change',()=>{mediaPage=1;renderMediaRows();});document.getElementById('add-media').addEventListener('click',()=>location.href='Register_QC_Media.html');renderMediaRows();
