'use strict';
const INSPECTION_ITEMS = ['Correct media name and product label','Lot number matches delivery document','Manufacturer details are legible','Container and seal are intact','No leakage or damaged plates/tubes','Media colour is acceptable','Media clarity is acceptable','No visible contamination','Agar depth or media volume is acceptable','No excessive dehydration or cracks','Quantity received matches order','Storage and transport condition acceptable'];
const tbody = document.getElementById('inspection-items');
tbody.innerHTML = INSPECTION_ITEMS.map((item,index)=>`<tr><td>${index+1}</td><td>${item}</td><td><select data-observation required><option value="">Select observation</option><option>Satisfactory</option><option>Unsatisfactory</option></select></td><td><input data-comment placeholder="Add comment"></td></tr>`).join('');
let checkedAt = '', checkedBy = '';
function progress(){ const done=[...document.querySelectorAll('[data-observation]')].filter(x=>x.value).length; document.getElementById('inspection-progress').textContent=`${done} / 12 completed`; }
document.querySelectorAll('[data-observation]').forEach(x=>x.addEventListener('change',progress));
document.getElementById('check-by').addEventListener('click',()=>{ checkedBy='Admin'; checkedAt=new Date().toISOString(); document.getElementById('checked-summary').textContent=`Admin · ${new Date(checkedAt).toLocaleString('en-MY')}`; });
document.getElementById('media-registration-form').addEventListener('submit',event=>{ event.preventDefault(); const form=event.currentTarget; if(!form.reportValidity()) return; const observations=[...document.querySelectorAll('[data-observation]')]; if(observations.some(x=>!x.value)){ observations.find(x=>!x.value).focus(); return; } if(!checkedAt){ document.getElementById('check-by').focus(); return; } const data=new FormData(form); const rows=QCMediaStore.read(); const record={id:QCMediaStore.nextId(rows),media:data.get('media'),lot:data.get('lot').trim(),manufacturer:data.get('manufacturer'),dateReceived:data.get('dateReceived'),checkedBy,checkedAt,status:'Pending',inspection:observations.map((select,index)=>({item:INSPECTION_ITEMS[index],observation:select.value,comment:document.querySelectorAll('[data-comment]')[index].value.trim()}))}; QCMediaStore.write([record,...rows]); const toast=document.getElementById('media-toast'); toast.textContent=`${record.id} registered successfully. Status: Pending.`; toast.hidden=false; setTimeout(()=>location.href=`Media_Performance_Testing.html?media=${encodeURIComponent(record.id)}`,900); });
